# Generated by Django 5.1.3 on 2024-12-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
